### ISSUE TITLE
Copyright Notice + License

### ISSUE THREAD

**Issue by stefanoschalkidis** [DJ-Raven/java-swing-switch-button#1]
Hi,

First of all a big thank you for all the great tutorials you published on YouTube and the code you shared on GitHub!

I would like to reuse this repo in one of the commercial applications I’m writing.

Therefore I would like to ask you if you would consider adding a copyright notice and a license to the repo?

Thanks a lot in advance.

**Comment by DJ-Raven** [comment]
It free

**Comment by stefanoschalkidis** [comment]
Awesome, thanks a lot and keep up the great work!
